### ISSUE TITLE
Logger for Sentry no longer active since PSR-3 introduction

### ISSUE THREAD

**Issue by kdambekalns** [flownative/flow-sentry#31]
The settings in https://github.com/flownative/flow-sentry/blob/f655f0f735dcee0656073a0826e72784910f5830/Configuration/Settings.yaml#L10-L14 are useless, it must be this instead:

```yaml
Neos:
  Flow:
    psr3:
      Neos\Flow\Log\PsrLoggerFactory:
        systemLogger:
          default:
            class: Flownative\Sentry\Log\SentryFileBackend
```
